# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f6c3de8e67478508f06290a7d429f6eb915df6fb697c0f069a5ab3525084a5e0907cf647a6c6625c0647015dafb373b34c12c0b4d099f7e56c8e1b18f327af2

test:
  secret_key_base: 49a237325cbde30c4696a0b39baf8a3412b3280d2b33d39c28570f2f3011833558cde26ac42aa7b93cab3a4548648b5c347d0779afeb8b37467382fb8340cd4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
